"""Document generators: professional DPR (PDF), BOQ (Excel), Route (KML)."""
import io
from datetime import date

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm, mm
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak,
    Image, Flowable,
)

import dpr_data as D

NAVY = colors.HexColor("#003087")
ORANGE = colors.HexColor("#FF6B00")
LIGHT = colors.HexColor("#f1f5f9")
GREY = colors.HexColor("#64748b")


# ----------------------------- PDF -----------------------------
class HRule(Flowable):
    def __init__(self, width, color=ORANGE, thickness=2):
        super().__init__(); self.width = width; self.color = color; self.thickness = thickness
    def draw(self):
        self.canv.setStrokeColor(self.color); self.canv.setLineWidth(self.thickness)
        self.canv.line(0, 0, self.width, 0)


def _styles():
    s = getSampleStyleSheet()
    s.add(ParagraphStyle("H1", parent=s["Heading1"], textColor=NAVY, fontSize=16, spaceBefore=10, spaceAfter=8))
    s.add(ParagraphStyle("H2", parent=s["Heading2"], textColor=ORANGE, fontSize=12, spaceBefore=8, spaceAfter=4))
    s.add(ParagraphStyle("Body2", parent=s["BodyText"], fontSize=9.5, leading=14, alignment=TA_JUSTIFY))
    s.add(ParagraphStyle("Small", parent=s["BodyText"], fontSize=8, textColor=GREY))
    return s


def _header_footer(canvas, doc):
    canvas.saveState()
    w, h = A4
    # header band (skip cover - page 1)
    if doc.page > 1:
        canvas.setFillColor(NAVY)
        canvas.rect(0, h - 1.4 * cm, w, 1.4 * cm, fill=1, stroke=0)
        canvas.setFillColor(colors.white)
        canvas.setFont("Helvetica-Bold", 9)
        canvas.drawString(1.5 * cm, h - 0.9 * cm, "RailPlan AI  ·  Detailed Project Report")
        canvas.setFont("Helvetica", 8)
        canvas.drawRightString(w - 1.5 * cm, h - 0.9 * cm, D.PROJECT["name"])
        canvas.setFillColor(ORANGE)
        canvas.rect(0, h - 1.45 * cm, w, 0.06 * cm, fill=1, stroke=0)
    # footer
    canvas.setStrokeColor(LIGHT); canvas.setLineWidth(0.5)
    canvas.line(1.5 * cm, 1.2 * cm, w - 1.5 * cm, 1.2 * cm)
    canvas.setFillColor(GREY); canvas.setFont("Helvetica", 7.5)
    canvas.drawString(1.5 * cm, 0.8 * cm, "Generated by RailPlan AI  ·  CONFIDENTIAL  ·  Demo Document")
    canvas.drawRightString(w - 1.5 * cm, 0.8 * cm, f"Page {doc.page}")
    canvas.restoreState()


def _tbl(data, col_widths, header=True, font=8, align_right=None):
    t = Table(data, colWidths=col_widths, repeatRows=1 if header else 0)
    style = [
        ("FONTSIZE", (0, 0), (-1, -1), font),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cbd5e1")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT]),
        ("TOPPADDING", (0, 0), (-1, -1), 3), ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ("LEFTPADDING", (0, 0), (-1, -1), 4), ("RIGHTPADDING", (0, 0), (-1, -1), 4),
    ]
    if header:
        style += [
            ("BACKGROUND", (0, 0), (-1, 0), NAVY),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ]
    if align_right:
        for c in align_right:
            style.append(("ALIGN", (c, 0), (c, -1), "RIGHT"))
    t.setStyle(TableStyle(style))
    return t


def build_dpr_pdf() -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=2.0 * cm, bottomMargin=1.6 * cm,
                            leftMargin=1.5 * cm, rightMargin=1.5 * cm, title="DPR")
    s = _styles()
    E = []
    P = D.PROJECT

    # ---------------- Cover ----------------
    E.append(Spacer(1, 2.0 * cm))
    # logo placeholder
    logo = Table([[""]], colWidths=[3 * cm], rowHeights=[3 * cm])
    logo.setStyle(TableStyle([
        ("BOX", (0, 0), (-1, -1), 2, ORANGE), ("BACKGROUND", (0, 0), (-1, -1), NAVY),
    ]))
    seal = Paragraph('<para align="center"><font color="white" size="9"><b>GOVERNMENT<br/>OF INDIA</b><br/>MINISTRY OF<br/>RAILWAYS</font></para>', s["BodyText"])
    cover_logo = Table([[seal]], colWidths=[3.4 * cm], rowHeights=[3.4 * cm])
    cover_logo.setStyle(TableStyle([
        ("BOX", (0, 0), (-1, -1), 2.5, ORANGE), ("BACKGROUND", (0, 0), (-1, -1), NAVY),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"), ("ALIGN", (0, 0), (-1, -1), "CENTER"),
    ]))
    E.append(Table([[cover_logo]], colWidths=[doc.width], style=[("ALIGN", (0, 0), (-1, -1), "CENTER")]))
    E.append(Spacer(1, 1.0 * cm))
    E.append(Paragraph('<para align="center"><font color="#64748b" size="11">GOVERNMENT OF INDIA · MINISTRY OF RAILWAYS</font></para>', s["BodyText"]))
    E.append(Spacer(1, 0.3 * cm))
    E.append(Paragraph(f'<para align="center"><font color="#003087" size="26"><b>DETAILED PROJECT REPORT</b></font></para>', s["BodyText"]))
    E.append(Spacer(1, 0.2 * cm))
    E.append(Table([[""]], colWidths=[6 * cm], style=[("LINEBELOW", (0, 0), (-1, -1), 2.5, ORANGE)]))
    E.append(Spacer(1, 0.8 * cm))
    E.append(Paragraph(f'<para align="center"><font color="#FF6B00" size="18"><b>{P["name"]}</b></font></para>', s["BodyText"]))
    E.append(Spacer(1, 0.2 * cm))
    E.append(Paragraph(f'<para align="center"><font size="12" color="#475569">{P["route"]}  ·  {P["distance_km"]} km  ·  {P["gauge"]}</font></para>', s["BodyText"]))
    E.append(Spacer(1, 2.5 * cm))
    meta = [
        ["Railway Zone", P["zone"]],
        ["Prepared by", P["prepared_by"]],
        ["Date of Report", date.today().strftime("%d %B %Y")],
        ["Estimated Cost", f"Rs. {P['total_cost_cr']:,} Crores"],
        ["Document Status", "For Internal Review (Demo)"],
    ]
    mt = Table(meta, colWidths=[5 * cm, 9 * cm])
    mt.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 10), ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("BACKGROUND", (0, 0), (0, -1), LIGHT),
        ("TEXTCOLOR", (0, 0), (0, -1), NAVY), ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
    ]))
    E.append(mt)
    E.append(PageBreak())

    def heading(num, title):
        E.append(Paragraph(f"{num}. {title}", s["H1"]))
        E.append(HRule(doc.width, ORANGE, 1.5)); E.append(Spacer(1, 6))

    # 1. Executive Summary
    heading("1", "Executive Summary")
    E.append(Paragraph(
        f"This Detailed Project Report presents the proposed <b>{P['name']}</b>, a {P['distance_km']} km "
        f"broad-gauge railway line under the {P['zone']}. The alignment ({P['route']}) was selected by the "
        "RailPlan AI optimisation engine after evaluating three candidate corridors against cost, "
        "constructability and environmental impact. Route B offers the lowest construction cost of "
        f"Rs. {P['total_cost_cr']:,} Crores while minimising forest disturbance and maintaining a constructible "
        "ruling gradient of 1 in 120. The project is expected to decongest the Raipur–Durg section of the "
        "Mumbai–Howrah trunk route, improve freight throughput and provide reliable regional connectivity.", s["Body2"]))
    E.append(Spacer(1, 6))
    summ = [["Parameter", "Value"],
            ["Total Length", f"{P['distance_km']} km"],
            ["Gauge", P["gauge"]],
            ["Electrification", P["electrified"]],
            ["Estimated Cost", f"Rs. {P['total_cost_cr']:,} Cr"],
            ["Ruling Gradient", "1 in 120"],
            ["Major Bridges", "5"], ["Stations", "4"],
            ["Implementation Period", "~7 years"]]
    E.append(_tbl(summ, [7 * cm, 7 * cm], align_right=[1]))

    # 2. Background
    heading("2", "Project Background & Objectives")
    E.append(Paragraph(
        "The existing Raipur–Durg corridor carries heavy mixed traffic and is approaching saturation. "
        "The objectives of this project are: (a) to add line capacity and decongest Raipur Junction; "
        "(b) to reduce transit time for coal and steel freight from the Chhattisgarh industrial belt; "
        "(c) to improve passenger connectivity for the Abhanpur–Dharsiwa region; and (d) to demonstrate "
        "AI-assisted alignment planning that lowers cost and environmental impact.", s["Body2"]))

    # 3. Route Survey
    heading("3", "Route Survey Details")
    surv = [["Chainage", "Location", "Latitude", "Longitude", "RL (m)"]]
    for ch, loc, la, lo, rl in D.SURVEY:
        surv.append([ch, loc, f"{la:.4f}", f"{lo:.4f}", str(rl)])
    E.append(_tbl(surv, [3 * cm, 4.2 * cm, 2.6 * cm, 2.6 * cm, 1.8 * cm], align_right=[2, 3, 4]))

    # 4. Terrain & Gradient
    heading("4", "Terrain & Gradient Analysis")
    E.append(Paragraph(
        "The terrain along Route B is predominantly flat to gently undulating (RL 289–316 m). Two gentle "
        "slopes were detected near Abhanpur and the Amner crossing; both are accommodated within the 1 in 120 "
        "ruling gradient without tunnelling. The AI optimiser flattened the longitudinal profile to reduce "
        "cut-and-fill earthwork by approximately 2.3 lakh cubic metres relative to the shortest-path option.", s["Body2"]))
    E.append(Spacer(1, 4))
    grad = [["Section", "Length (km)", "Ruling Gradient", "Remarks"],
            ["Raipur–Abhanpur", "18.2", "1 in 150", "Flat"],
            ["Abhanpur–Amner", "16.4", "1 in 120", "Gentle slope"],
            ["Amner–Dharsiwa", "17.5", "1 in 130", "Gentle slope"],
            ["Dharsiwa–Durg", "19.7", "1 in 160", "Flat"]]
    E.append(_tbl(grad, [5 * cm, 3 * cm, 3.5 * cm, 3 * cm], align_right=[1]))

    # 5. Hydrology & Bridge Schedule
    heading("5", "Hydrology & Bridge Schedule")
    E.append(Paragraph("A total of 12 water crossings were identified. Five major bridges are scheduled below; "
                       "nine minor bridges and culverts handle the remaining crossings.", s["Body2"]))
    E.append(Spacer(1, 4))
    br = [["Bridge No", "Location", "River / Stream", "Span", "Type", "Cost (Rs. Cr)"]]
    for row in D.BRIDGES:
        br.append(list(row))
    E.append(_tbl(br, [2.2 * cm, 2.2 * cm, 3.4 * cm, 2.6 * cm, 2.4 * cm, 2.4 * cm], align_right=[5]))

    # 6. Land Acquisition
    heading("6", "Land Acquisition Details")
    L = D.LAND_SUMMARY
    E.append(Paragraph(
        f"The corridor requires acquisition of <b>{L['total_ha']} hectares</b> across "
        f"{len(L['villages'])} villages ({', '.join(L['villages'])}), affecting an estimated "
        f"{L['households']} households. The compensation estimate is Rs. {L['compensation_cr']} Crores with an "
        f"acquisition timeline of {L['timeline']}.", s["Body2"]))
    E.append(Spacer(1, 4))
    land = [["Land Use", "Share (%)", "Area (Ha)"]]
    for u in D.LAND_USE:
        land.append([u["type"], f"{u['pct']}%", f"{u['ha']}"])
    land.append(["TOTAL", "100%", f"{L['total_ha']}"])
    E.append(_tbl(land, [6 * cm, 4 * cm, 4 * cm], align_right=[1, 2]))

    # 7. Environment
    heading("7", "Environmental Considerations")
    E.append(Paragraph(
        "Route B was specifically optimised to avoid the Sitanadi reserve buffer, reducing forest land "
        "requirement to 21.5 hectares (65% lower than the shortest-path alignment). Afforestation at a 1:2 "
        "ratio, noise barriers near settlements, and wildlife underpasses are budgeted under environmental "
        "mitigation. The project falls under Stage-I/II Forest Clearance for the limited forest stretch.", s["Body2"]))

    # 8. Cost Estimate
    heading("8", "Detailed Cost Estimate")
    cost = [["Cost Head", "Amount (Rs. Cr)", "Share"]]
    for c in D.COST_SPLIT:
        cost.append([c["head"], f"{c['amount']}", f"{c['pct']}%"])
    cost.append(["TOTAL", f"{P['total_cost_cr']}", "100%"])
    ct = _tbl(cost, [7 * cm, 4 * cm, 3 * cm], align_right=[1, 2])
    E.append(ct)

    # 9. BOQ
    E.append(PageBreak())
    heading("9", "Bill of Quantities (Abstract)")
    boq = [["Sr", "Item", "Unit", "Qty", "Rate (Rs.)", "Amount (Rs. Cr)"]]
    for sr, item, unit, qty, rate, amt in D.BOQ:
        boq.append([sr, item, unit, qty, f"{rate:,}" if isinstance(rate, int) else rate, amt])
    E.append(_tbl(boq, [1 * cm, 6.4 * cm, 1.3 * cm, 2.0 * cm, 2.4 * cm, 2.3 * cm], font=7.2, align_right=[3, 4, 5]))

    # 10. Implementation Schedule
    heading("10", "Implementation Schedule")
    sched = [["Phase", "Duration", "Start (month)", "Finish (month)"]]
    for t in D.TIMELINE:
        sched.append([t["phase"], f"{t['months']} months", f"M{t['start']}", f"M{t['start'] + t['months']}"])
    sched.append(["TOTAL (overlapping)", "~7 years", "M0", f"M{D.TIMELINE_TOTAL_MONTHS}"])
    E.append(_tbl(sched, [6.5 * cm, 3 * cm, 2.5 * cm, 2.5 * cm], align_right=[1, 2, 3]))

    # 11. Conclusion
    heading("11", "Conclusion & Recommendations")
    E.append(Paragraph(
        f"Route B (AI Optimized) is recommended for implementation. It delivers the lowest lifecycle cost "
        f"(Rs. {P['total_cost_cr']:,} Cr), the smallest environmental footprint, and a fully constructible "
        "alignment. RailPlan AI generated this report in hours rather than the months required by conventional "
        "methods. It is recommended that detailed ground survey and Stage-II forest clearance be initiated "
        "immediately to maintain the projected 7-year implementation schedule.", s["Body2"]))
    E.append(Spacer(1, 16))
    E.append(Paragraph('<para align="right"><font color="#64748b" size="9"><i>— End of Report —</i></font></para>', s["BodyText"]))

    doc.build(E, onFirstPage=_header_footer, onLaterPages=_header_footer)
    return buf.getvalue()


# ----------------------------- Excel BOQ -----------------------------
def build_boq_xlsx() -> bytes:
    from openpyxl import Workbook
    from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
    from openpyxl.utils import get_column_letter

    wb = Workbook()
    ws = wb.active
    ws.title = "BOQ"
    navy = "FF003087"; orange = "FFFF6B00"; light = "FFF1F5F9"
    thin = Side(style="thin", color="FFCBD5E1")
    border = Border(left=thin, right=thin, top=thin, bottom=thin)

    # title
    ws.merge_cells("A1:F1")
    ws["A1"] = "RailPlan AI — Bill of Quantities"
    ws["A1"].font = Font(bold=True, size=15, color="FFFFFFFF")
    ws["A1"].fill = PatternFill("solid", fgColor=navy)
    ws["A1"].alignment = Alignment(horizontal="center", vertical="center")
    ws.row_dimensions[1].height = 26
    ws.merge_cells("A2:F2")
    ws["A2"] = f"{D.PROJECT['name']}  ·  {D.PROJECT['route']}  ·  {D.PROJECT['distance_km']} km"
    ws["A2"].font = Font(italic=True, size=10, color="FF475569")
    ws["A2"].alignment = Alignment(horizontal="center")

    headers = ["Sr", "Item", "Unit", "Qty", "Rate (Rs.)", "Amount (Rs. Cr)"]
    ws.append([])
    ws.append(headers)
    hr = ws.max_row
    for c in range(1, 7):
        cell = ws.cell(row=hr, column=c)
        cell.font = Font(bold=True, color="FFFFFFFF")
        cell.fill = PatternFill("solid", fgColor=orange)
        cell.alignment = Alignment(horizontal="center", vertical="center")
        cell.border = border

    total = 0.0
    for sr, item, unit, qty, rate, amt in D.BOQ:
        ws.append([sr, item, unit, qty, (f"{rate:,}" if isinstance(rate, int) else rate), float(amt)])
        total += float(amt)
        r = ws.max_row
        for c in range(1, 7):
            cell = ws.cell(row=r, column=c); cell.border = border
            if r % 2 == 0:
                cell.fill = PatternFill("solid", fgColor=light)
        ws.cell(row=r, column=6).number_format = '#,##0.00'

    # total row
    ws.append(["", "TOTAL", "", "", "", round(total, 2)])
    tr = ws.max_row
    for c in range(1, 7):
        cell = ws.cell(row=tr, column=c)
        cell.font = Font(bold=True, color="FFFFFFFF"); cell.fill = PatternFill("solid", fgColor=navy)
        cell.border = border
    ws.cell(row=tr, column=6).number_format = '#,##0.00'

    widths = [6, 46, 8, 14, 16, 16]
    for i, w in enumerate(widths, 1):
        ws.column_dimensions[get_column_letter(i)].width = w
    ws.freeze_panes = "A5"

    buf = io.BytesIO(); wb.save(buf); return buf.getvalue()


# ----------------------------- KML -----------------------------
def build_route_kml() -> str:
    coords = [
        (21.2514, 81.6296, "Raipur"),
        (21.0900, 81.5400, "Abhanpur"),
        (21.1450, 81.3900, "Dharsiwa"),
        (21.1900, 81.2833, "Durg"),
    ]
    line = " ".join(f"{lo},{la},0" for la, lo, _ in coords)
    placemarks = "".join(
        f'<Placemark><name>{n}</name><Point><coordinates>{lo},{la},0</coordinates></Point></Placemark>'
        for la, lo, n in coords)
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <name>RailPlan AI - {D.PROJECT['name']}</name>
    <description>{D.PROJECT['route']} - {D.PROJECT['distance_km']} km - Generated by RailPlan AI</description>
    <Style id="routeB"><LineStyle><color>ff00cc4c</color><width>4</width></LineStyle></Style>
    <Placemark>
      <name>Route B - AI Optimized</name>
      <styleUrl>#routeB</styleUrl>
      <LineString><tessellate>1</tessellate><coordinates>{line}</coordinates></LineString>
    </Placemark>
    {placemarks}
  </Document>
</kml>"""
